[[redirects]]
from = "/issuance/*"
to = "https://temp-hpass.duckdns.org/issuance/:splat"
status = 200
force = true
headers = { Access-Control-Allow-Origin = "*"}


[[redirects]]
from = "https://hpass-issuance.netlify.app/issuance/dgca-issuance-service/dgci/issue"
to = "https://temp-hpass.duckdns.org/issuance/dgca-issuance-service/dgci/issue"
status = 200
force = true
headers = { Access-Control-Allow-Origin = "*"}


[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"