[[redirects]]
from = "/issuance/**"
to = "https://temp-hpass.duckdns.org/issuance/:splat"
status = 200
headers = { Access-Control-Allow-Origin = "*"}

[[redirects]]
from = "https://hpass-issuance.netlify.app/issuance/**"
to = "https://temp-hpass.duckdns.org/issuance/:splat"
status = 200
headers = { Access-Control-Allow-Origin = "*"}

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"